schema {
  query: Query
  mutation: Mutation
}

type Query {
  learner(lid: ID!): Learner
  learners(criteria: LearnerBioSearch!): [Learner]
  book(bid: String!): Book
}

type Mutation {
  signup(info: LearnerBioSignup): Learner
}

type Learner {
  lid: ID!
  bio: LearnerBio!
}

input LearnerBioSearch {
  name: String
}

type LearnerBio {
  name: String
  age: Int
}

input LearnerBioSignup {
  name: String
  age: Int
}

type Book {
  bid: String!
  title: String,
  author: String,
  SBN: String@deprecated(reason: "Replaced with the international standard. Please use ISBN instead."),
  ISBN: String
}